---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
{{ include "cat-application.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
    spec:
        containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
            ports:
              - name: http
                containerPort: 8080
            readinessProbe:
              httpGet:
                path: /cats
                port: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
{{ include "cat-application.labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
  ports:
    - port: 80
      targetPort: http
