#!/bin/bash

sudo apt update
sudo apt install -y default-jre
java -version

sudo adduser --system --group hello

sudo cp /vagrant/hello.service /etc/systemd/system/
sudo systemctl daemon-reload
sudo systemctl enable hello
sudo systemctl start hello
