#!/bin/bash

sudo apt-get update
sudo apt-get -y install default-jre
java -version
sudo cp /vagrant/hello.service /etc/systemd/system/
sudo systemctl daemon-reload
sudo systemctl enable hello
sudo systemctl start hello
