#!/bin/bash

apt update
apt install -y default-jre

adduser --system --group hello

# install application
sudo --user=hello curl --location --output /home/hello/hello-spring-boot-0.1.0.jar https://github.com/adyang/infrastructure-101-guild/raw/master/week1/hello-spring-boot-0.1.0.jar
cat <<EOF | sudo --user=hello tee /home/hello/application.properties >/dev/null
server.port=5000
app.greeting=Greetings from ${HOSTNAME},
EOF

# configure systemd
cat <<EOF >/etc/systemd/system/hello.service
[Unit]
Description=Hello World Spring Boot
StartLimitIntervalSec=30s
StartLimitBurst=5

[Service]
ExecStart=/usr/bin/java -jar /home/hello/hello-spring-boot-0.1.0.jar --spring.config.location=file:///home/hello/application.properties
User=hello
Group=hello
Restart=always
RestartSec=3s

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable hello
systemctl start hello
