---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meow
  labels:
    app: meow
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meow
  template:
    metadata:
      labels:
        app: meow
    spec:
      containers:
        - name: meow-application
          image: janesee3/meow-application:1
          envFrom:
            - configMapRef:
                name: meow-env
